name: docs
on:
  push:
    branches:
      - main
      - release
      - development
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - run: |
          pip install lazydocs mkdocs mkdocs-awesome-pages-plugin
      - run: ./build-docs.sh
      - run: mkdocs gh-deploy --force
      